config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',
                     path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret',
                                   confirmation: 'verification', unlock: 'unblock', registration: 'register',
                                  sign_up: 'join' }

  root to: 'recipes#index'

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  resources :shopping_lists, only: [:index] do
    collection do
      get 'generate'
    end
  end
  id_pattern = /\d+/
  # id must match a number for at least one digit
  constraints(id: id_pattern, user_id: id_pattern, recipe_id: id_pattern, food_id: id_pattern, recipe_food_id: id_pattern) do
    resources :public_recipes, only: %i[index]
    resources :recipe_foods, only: %i[new create edit update destroy]

    resources :users, only: %i[new create]

    resources :foods, only: %i[index new create destroy]
    resources :recipes, only: %i[index show new create destroy] do
      member do
        patch 'update', to: 'recipes#update', as: 'update'
      end
    end
  end

end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @public_recipes = Recipe.includes(recipe_foods: [:food]).is_public.order(created_at: :desc)
  end
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/views/public_recipes/_link_layout.html.erb
<%= link_to recipe_path(public_recipe.id) do %>
  <%= yield %>
<% end %>

app/views/public_recipes/_public_index.html.erb
<%= render partial: 'public_recipe', layout: 'link_layout', collection: public_recipes %>

app/views/public_recipes/_public_recipe.html.erb
<div class="pub-display-cont">
  <div class="pub-info">
    <h2><%= public_recipe %></h2>
    <p>by: <span><%= public_recipe.user %></span></p>
  </div>
  <div class="totals">
    <p>Food items: <span><%= public_recipe.total_items %></span></p>
    <p>Total price: <span><%= number_to_currency(public_recipe.total_price, precision: 2, format: '%u %n') %></span></p>
  </div>
</div>

app/views/public_recipes/_section_layout.html.erb
<section id="recipes-list">
  <%= yield %>
</section>

app/views/public_recipes/index.html.erb
<h1>Public Recipes</h1>
<%= render partial: 'public_index', layout: 'section_layout', locals: { public_recipes: @public_recipes } %>