config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',
                     path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret',
                                   confirmation: 'verification', unlock: 'unblock', registration: 'register',
                                  sign_up: 'join' }

  root to: 'recipes#index'

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  resources :shopping_lists, only: [:index] do
    collection do
      get 'generate'
    end
  end
  id_pattern = /\d+/
  # id must match a number for at least one digit
  constraints(id: id_pattern, user_id: id_pattern, recipe_id: id_pattern, food_id: id_pattern, recipe_food_id: id_pattern) do
    resources :public_recipes, only: %i[index]
    resources :recipe_foods, only: %i[new create edit update destroy]

    resources :users, only: %i[new create]

    resources :foods, only: %i[index new create destroy]
    resources :recipes, only: %i[index show new create destroy] do
      member do
        patch 'update', to: 'recipes#update', as: 'update'
      end
    end
  end

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, :preparation_time, :cooking_time, :description, presence: { message: 'must be provided' }
  validates :name, format: { with: /\A[a-z ,.'-]+\z/i, message: 'provided `%<value>s` is not a valid' },
                   allow_nil: false, allow_blank: false
  validates :name, length: { minimum: 3, too_short: 'must be at least %<count>s characters' }
  validates :name, length: { maximum: 150, too_long: "can't exceed %<count>s characters" }

  validates :preparation_time, numericality: { greater_than: 0, message: 'must be greater than zero' }
  validates :cooking_time, numericality: { greater_than: 0, message: 'must be greater than zero' }

  belongs_to :user
  has_many :recipe_foods, inverse_of: :recipe, dependent: :destroy
  has_many :foods, through: :recipe_foods

  scope :is_public, -> { where(public: true) }

  def total_items
    recipe_foods.count
  end

  def total_price
    recipe_foods.sum do |rf|
      rf.quantity * rf.food.price
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_ability

  def set_ability
    @ability = Ability.new(current_user)
  end

  def index
    @recipes = Recipe.where(user: current_user)
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe was successfully created.'
    else
      render 'new'
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.toggle(:public)
    if @recipe.save
      flash[:notice] = update_recipe_notice
      redirect_to recipe_path(@recipe), status: :see_other
    else
      redirect_to recipe_path(@recipe), status: 304, alert: @recipe.errors.full_messages.first
    end
  end

  def show
    @recipe = Recipe.includes(recipe_foods: [:food]).find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def destroy
    Recipe.find(params[:id]).destroy
    redirect_to recipes_path
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipe_path(@recipe), notice: 'Recipe Food was successfully destroyed.'
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time)
  end

  def update_recipe_notice
    "Recipe was succesfully #{@recipe.public? ? 'added to' : 'removed from'} the 'Public Recipes List'"
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def confirm_toggle_public
    confirm_message = ["Do you want to #{@recipe.public ? 'remove' : 'add'} the Recipe"]
    confirm_message << ["#{@recipe.public ? 'from' : 'to'} the 'Public Recipes List'"]
    confirm_message.join(' ')
  end
end

app/views/recipes/index.html.erb
<h1> Recipe List </h1>
<div class="recipe-pages-list-recip-cont">
  <div class="recipe-pages-inner-list-recip-cont">
    <%= link_to new_recipe_path do %>
       Add a Recipe
    <% end %>
  </div>
</div>
    <div class="recipe-page-card-container">
        <% @recipes.each do |recipe| %>
          <div class = "recipe-card">
            <%= link_to recipe_path(recipe) do %>
              <div class = "inner-recipe-card">
                <div class= "name-and-rmvbtn">
                  <h2>
                    <%= recipe.name %>
                  </h2>

                </div>
                <div>
                  <p>Description:
                    <span>
                      <%= recipe.description %>
                    </span>
                  </p>
                </div>
              </div>
            <% end %> 
            <% if can? :destroy, recipe %>
            <%= form_with model: recipe, url: recipe_path(recipe), method: :delete do |form| %>
              <%= form.submit "Remove", class: "rmv-btn" %>
            <% end %>
            <% end %>
          </div>
        <% end %>
      </div>

app/views/recipes/new.html.erb
<div class="recipe-new-top-container">
    <div class="recipe-new-inner-container">
        <h1>Add New Recipe</h1>

        <%= form_with model: @recipe, url: recipes_path do |form| %>
            <div>
                <%= form.label :name, class: "label-name" %>
            </div>
            <div>
                <%= form.text_field :name, class: "input-fiel" %>
            </div>

            <div>
                <%= form.label :preparation_time, class: "label-name" %> (* Must be specified n hours)
            </div>
            <div>
                <%= form.number_field :preparation_time,  step: '0.25', class: "input-fiel", placeholder: "0.25 = 15Min" %>
            </div>

            <div>
                <%= form.label :cooking_time, class: "label-name" %> (* Must be specified in hours)
            </div>
            <div>
                <%= form.number_field :cooking_time,  step: '0.25', class: "input-fiel", placeholder: "0.25 = 15 Min" %>
            </div>

            <div>
                <%= form.label :description, class: "label-name" %>
            </div>
            <div>
                <%= form.text_area :description, rows: 6, style: 'width:90%; margin: 0.5rem 0' %>
            </div>

            <div class="submt-btn-div">
                <%= form.submit "Add Recipe", class: "submit-btn" %>
            </div>
        <% end %>
    </div>
</div>

app/views/recipes/show.html.erb
<% if can? :read, @recipe %>
<div class = "recipe-show-top-container">
  <div class = "recipe-show-inner-container">
    <h1>
      <%= @recipe.name %>
    </h1>
    <div class = "prep-time-public">
        <p>
          <strong>Preparation time</strong>: <%= @recipe.preparation_time %> hour
        </p>
        <div class = "publi">
        <% if user_signed_in? and can? :update, @recipe %>
        <div class = "public">
          <%= label_tag do %>
            <strong>Public</strong>
          <% end %>
          <%= label_tag '', class: 'switch' do %>
            <%= link_to [:update, @recipe], data: { turbo_method: :patch, turbo_confirm: confirm_toggle_public } do %>
              <%= check_box('recipe', :public, { class: 'public_check' }, true, false) %>
              <span class="slider round"></span>
            <% end %>
          <% end %>
        </div>
      <% end %>	
        </div>
    </div>
    <p>
      <strong>Cooking time</strong>: <%= @recipe.cooking_time %> hour
    </p>
    <p class="descr-top">
      <strong>Steps to Cook</strong>: 
      <p class="descr">
        <%= @recipe.description %>
      </p>
    </p>
    <% if can? :update, @recipe %>
      <div class="shop-ingrid-container">
        <%= link_to generate_shopping_lists_path(recipe_id: @recipe.id) do %>     
          <button>Generate Shopping List</button>
        <% end %>
        <%= link_to new_recipe_food_path(recipe_id: @recipe.id) do %>
          <button>Add Ingredient</button>
        <% end %>
      </div>
    <% end %>
  </div>
  <div>
      <table class="customers">
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Value</th>
          <% if can? :destroy, @recipe %>
            <th>Actions</th>
          <% end %>
        </tr>
        <% @recipe.recipe_foods.each do |food| %>
          <tr>
            <td><%= food.food.name %></td>
            <td><%= "#{food.quantity} #{food.food.measurement_unit}" %></td>
            <td>$<%= food.food.price * food.quantity %></td>
            <td>
              <div class="table-td-div">
                <% if can? :destroy, @recipe %>
                  <%= form_with model: food, url: recipe_food_path(food), method: :delete do |form| %>
                    <%= form.submit "Remove", class: "recipe-show-remove-btn" %>
                  <% end %>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </table>
  </div>
</div>
<% else %>
 <%= link_to 'See Public Recipe', public_recipes_path %>
<% end %>