config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',
                     path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret',
                                   confirmation: 'verification', unlock: 'unblock', registration: 'register',
                                  sign_up: 'join' }

  root to: 'recipes#index'

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  resources :shopping_lists, only: [:index] do
    collection do
      get 'generate'
    end
  end
  id_pattern = /\d+/
  # id must match a number for at least one digit
  constraints(id: id_pattern, user_id: id_pattern, recipe_id: id_pattern, food_id: id_pattern, recipe_food_id: id_pattern) do
    resources :public_recipes, only: %i[index]
    resources :recipe_foods, only: %i[new create edit update destroy]

    resources :users, only: %i[new create]

    resources :foods, only: %i[index new create destroy]
    resources :recipes, only: %i[index show new create destroy] do
      member do
        patch 'update', to: 'recipes#update', as: 'update'
      end
    end
  end

end

app/models/food.rb
class Food < ApplicationRecord
  validates :name, :measurement_unit, :price, :quantity, presence: { message: 'must be provided' }
  validates :name, format: { with: /\A[a-z ,.'-]+\z/i,
                             message: 'provided `%<value>s` is not a valid' },
                   allow_nil: false, allow_blank: false
  validates :name, length: { minimum: 3, too_short: 'must be at least %<count>s characters' }
  validates :name, length: { maximum: 65, too_long: "can't exceed %<count>s characters" }
  validates :name, uniqueness: { scope: :user, case_sensitive: false,
                                 message: 'provided `%<value>s` seems that it already exists' }
  validates :measurement_unit, length: { minimum: 2, too_short: 'must be at least %<count>s characters' }
  validates :measurement_unit, length: { maximum: 30, too_long: "can't exceed %<count>s characters" }
  validates :measurement_unit, uniqueness: { scope: %i[user name],
                                             message: 'provided `%<value>s` seems that it already exists' }
  validates :price, numericality: { greater_than: 0, message: 'must be greater than zero' }
  validates :quantity, numericality: { greater_than: 0, message: 'must be greater than zero' }

  belongs_to :user
  has_many :recipe_foods, inverse_of: :food, dependent: :destroy
  has_many :recipes, through: :recipe_foods
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.where(user: current_user)
  end

  def new
    params = session_params
    @food = params ? Food.new(params) : Food.new
    @food.user = current_user
  end

  def create
    @food = current_user.foods.build(food_params)

    if @food.save
      session.delete(:new_food) if session[:new_food]
      redirect_to foods_path, notice: "Food #{@food.name} was added succesfully!"
    else
      flash[:alert] = @food.errors.full_messages.first
      session[:new_food] = @food
      redirect_to new_food_path
    end
  end

  def destroy
    @food = Food.where(user: current_user).find(params[:id])
    redirect_to foods_path, notice: "Food #{@food.name} was deleted!" and return if @food.destroy

    redirect_to foods_path, alert: 'Something went wrong while trying to delete the Food'
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end

  def session_params
    return false if session[:new_food].nil?

    session[:new_food].filter do |key|
      %w[name measurement_unit price quantity].include? key
    end
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
  def create_column_name(column_name)
    column_words = column_name.split('_')
    column_words.map(&:capitalize).join(' ')
  end
end

app/views/foods/_food.html.erb
<%= food %>

app/views/foods/_food_row.html.erb
<tr>
  <td>
    <%= food_row.name %>
  </td>
  <td>
    <%= food_row.measurement_unit %>
  </td>
  <td>
    <%= number_to_currency(food_row.price, precision: 2, format: '%u %n') %>
  </td>
  <td>
    <%= food_row.quantity %>
  </td>
  <td>
    <%= link_to 'Delete', food_path(food_row), data: { turbo_method: :delete, turbo_confirm: "Delete Food: #{food_row.name} ?" }, class: "food-delete-btn" %>
  </td>
</tr>

app/views/foods/_foods.html.erb
<%= render partial: 'food_row', collection: @foods %>

app/views/foods/_table_layout.html.erb
<table class="foods-table customers">
  <tr>
    <% columns.each do |column_name| %>
      <th><%= create_column_name(column_name) %></th>
    <% end %>
  </tr>
  <tbody>
    <%= yield %>
  </tbody>
</table>

app/views/foods/index.html.erb
<div class = "top-container">
  <div class = "inner-container">
    <h1> Food List </h1>
    <div class="add-food-link-cont">
      <div class = "add-food-link">
        <%= link_to 'Add Food', new_food_path %>
      </div>
    </div>
    <%= render partial: 'foods', layout: 'table_layout', locals: { foods: @foods, columns: %w[name measurement_unit unit_price Total_Quantity actions] } %>
  </div>
</div>

app/views/foods/new.html.erb
<div class="top-container">
    <div class="inner-container food-form-inner-cont">
        <h1>Add New Food</h1>
        <%= form_with model: @food, url: foods_path do |form| %>
        <div class="field">
            <%= form.label :name, class: ".label-name" %>
        </div>

        <div class="field">
            <%= form.text_field :name, autofocues: true, class: 'input-fiel' %>
        </div>

        <div class="field">
            <%= form.label :measurement_unit, class: ".label-name" %>
        </div>
        <div class="field">
            <%= form.text_field :measurement_unit, class: 'input-fiel' %>
        </div>

        <div class="field">
            <%= form.label :price, class: ".label-name" %>
        </div>
        <div class="field">
            <%= form.number_field :price, step: 0.1, class: 'input-fiel' %>
        </div>

        <div class="field">
            <%= form.label :quantity, class: ".label-name" %>
        </div>
        <div class="field">
            <%= form.number_field :quantity, step: 1, class: 'input-fiel' %>
        </div>

        <div class="actions">
            <%= form.submit "Add Food", class: "submit-btn" %>
        </div>
        <% end %>
    </div>
</div>