config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',
                     path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret',
                                   confirmation: 'verification', unlock: 'unblock', registration: 'register',
                                  sign_up: 'join' }

  root to: 'recipes#index'

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  resources :shopping_lists, only: [:index] do
    collection do
      get 'generate'
    end
  end
  id_pattern = /\d+/
  # id must match a number for at least one digit
  constraints(id: id_pattern, user_id: id_pattern, recipe_id: id_pattern, food_id: id_pattern, recipe_food_id: id_pattern) do
    resources :public_recipes, only: %i[index]
    resources :recipe_foods, only: %i[new create edit update destroy]

    resources :users, only: %i[new create]

    resources :foods, only: %i[index new create destroy]
    resources :recipes, only: %i[index show new create destroy] do
      member do
        patch 'update', to: 'recipes#update', as: 'update'
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navigation.html.erb
<nav>
    
    <ul>
        <% if user_signed_in? %>
          <span class="logged-in-user"><h3>Hi, <%= current_user %></h3></span>
          <li><a href="<%= foods_path %>" link-ref>Food</a></li>
          <li><a href="<%= recipes_path %>" link-ref>Recipes</a></li>
          <li><a href="<%= public_recipes_path %>" link-ref>Public Recipes</a></li>
          <li><a href="<%= users_sign_out_path %>" link-ref>Log out</a></li>
        <% else %>
          <li><a href="<%= public_recipes_path %>" link-ref>Public Recipes</a></li>
          <li><a href="<%= new_user_session_path %>" link-ref>Log In</a></li>
          <li><a href="<%= new_user_registration_path %>" link-ref>Join</a></li>
        <% end %>
    </ul>
</nav>
<script>
  document.addEventListener("turbo:load", function () {
    const currentPath = "<%= request.path %>";
    const navLinks = document.querySelectorAll("[link-ref]");

    navLinks.forEach((link) => {
      link.classList.remove("active-link");

      if (link.getAttribute("href") === currentPath) {
        link.classList.add("active-link");
      }
    });
  });
</script>